# 开发环境配置
environment: 'development'
app:
  prefix: '/api'
  port: 8082
  swagger: true
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
  # 文件相关
  file:
    # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
    location: '../upload'
    # 文件服务器地址
    domain: 'http://localhost:8081'
    # 文件虚拟路径, 必须以 / 开头
    serveRoot: '/static'
# 数据库配置
db:
  mysql:
    host: '127.0.0.1'
    username: 'root'
    password: '123123qq'
    database: 'mallshop'
    port: 3307

# redis 配置
redis:
  host: '127.0.0.1'
  port: 6389
  db: 0
  password: '123456'
  token_expire: 1800000
# jwt 配置
jwt:
  secret: 'jktusernamemallqwer'
  expiresIn: 1600
